baseURL = "https://mcclatchy.github.io/design"
title = "McClatchy Design"

languageCode = "en-us"
relativeURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "borland"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "404"]

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "style guide"
    url = "/saratoga/"
    weight = 1
  [[menu.main]]
    name = "markets"
    url = "/markets/"
    weight = 2
  [[menu.main]]
    name = "labs"
    url = "/labs/"
    weight = 3
